/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.hexlet;

public class App {
	public String getGreeting() {
		return "Welcome to the Mind Games!";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());
	}
}
